### ISSUE TITLE
How do I run export GOOGLE_APPLICATION_CREDENTIALS=path/to/service/account.json in anaconda?

### ISSUE THREAD

**Issue by scaruslooner** [LamboCreeper/speech-control#1]
Hi, Im using anconda(IDE) with python 3.6
Also im on windows.

I encounter this error after trying to do (python3 video-mashup <source> <destination> <sentence>)  , "google.auth.exceptions.DefaultCredentialsError: The file C:\Users\camer\Desktop\Video projects__SCRIPTS_VIDEOMASHUP\client_secret_672522134118-dv5sbe08lbtdi7f9o38k52albg7ms37v.apps.googleusercontent.com.json does not have a valid type. Type is None, expected one of ('authorized_user', 'service_account', 'external_account', 'impersonated_service_account')."
 
I think the problem is Im not setting variable correctly in anconda(IDE). I use this to setup my google credentials :

https://i.stack.imgur.com/w61E8.png

It returned nothing so I thought it worked. Then, I ran the next line of code (python3 video-mashup <source> <destination> <sentence>) and got this error:

https://i.stack.imgur.com/OJDFY.png

Also, I when ran the code, you can see on the first line, I change python3 to python because the code wasnt finding the python.

So, How do I "5. Run export GOOGLE_APPLICATION_CREDENTIALS=path/to/service/account.json" correctly in anaconda?

**Comment by LamboCreeper** [comment]
Hi, thanks for raising this issue! How are you generating this service account? Based on the error I'm suspecting it might be in the wrong format (specifically missing the `type` field). It should look like the service account on [this](https://cloud.google.com/iam/docs/creating-managing-service-account-keys) page.

**Comment by scaruslooner** [comment]
### So I tried new run today and here the steps I did.

1. **I created environment in anconda**

conda create -n MASH2 python=3.6 

2. **I created a directory**

Cd C:\Users\camer\Desktop\Video projects\__SCRIPTS\_2VIDEOMASHUP

3. **After I install the three dependencies**

pip install ...


4. **I made account for google services and generated and added the json file to my project folder**
![image](https://user-images.githubusercontent.com/39450507/156822983-3c0aead8-04e6-44e1-8584-b85a17317b78.png)
![image](https://user-images.githubusercontent.com/39450507/156823057-2e6dd009-83e2-4782-a120-7407be2c1d2b.png)


5. **I think this is how im generating the service account, I use what _set_ instead of _export_**
**_(i think im using the right format)_**

![image](https://user-images.githubusercontent.com/39450507/156824490-8e9717fb-8681-4484-86a4-78747a11b7dc.png)


set GOOGLE_APPLICATION_CREDENTIALS= C:\Users\camer\Desktop\Video projects\__SCRIPTS\_2VIDEOMASHUP\client_secret_672522134118-dv5sbe08lbtdi7f9o38k52albg7ms37v.apps.googleusercontent.com.json

![image](https://user-images.githubusercontent.com/39450507/156823601-93dadba6-5225-416a-ab06-aa8c27279544.png)

**(nothing happens after this)**


6. **Then I try to generate it**
Python __main__.py  ./sp.mp4 ./final.mp4 "I will still love you, why are your hands so sweaty"
![image](https://user-images.githubusercontent.com/39450507/156823601-93dadba6-5225-416a-ab06-aa8c27279544.png)
(I get error message of google.auth.exceptions.DefaultCredentialsError: File  C:\Users\camer\Desktop\Video projects\__SCRIPTS\_2VIDEOMASHUP\client_secret_672522134118-dv5sbe08lbtdi7f9o38k52albg7ms37v.apps.googleusercontent.com.json was not found.)

**Comment by LamboCreeper** [comment]
Ah, so it looks like you've created an API OAuth2 client ID rather than an IAM Service account. You'll want to:
1. Go to https://console.cloud.google.com/iam-admin/serviceaccounts
2. Create a new service account
3. Click into the newly created service account
4. Go to the "keys" tab
5. Click "Add key" then "create new key"
6. Select "JSON" and save - the correct file should download to your computer

**Comment by scaruslooner** [comment]
Ok I did the steps above and reran it and encountered the same problem: 
![image](https://user-images.githubusercontent.com/39450507/156899273-5c17280c-2f5e-452f-ba60-9bfd4e34223e.png)

The error message: google.auth.exceptions.DefaultCredentialsError: File  C:\Users\camer\Desktop\Video projects\__SCRIPTS\_2VIDEOMASHUP\pragmatic-mote-340205-78677dda5561.json was not found.

**Comment by LamboCreeper** [comment]
It looks like your adding an extra space when setting the environment variable. Try removing that and seeing if it helps.
![image](https://user-images.githubusercontent.com/12111454/157241603-ebdae123-5cb0-44ca-8339-9211330a8105.jpeg)

**Comment by scaruslooner** [comment]
### That fixed issue but then I ran into another error:

(MASH2) C:\Users\camer>Cd C:\Users\camer\Desktop\Video projects\__SCRIPTS\_2VIDEOMASHUP

(MASH2) C:\Users\camer\Desktop\Video projects\__SCRIPTS\_2VIDEOMASHUP>set GOOGLE_APPLICATION_CREDENTIALS=C:\Users\camer\Desktop\Video projects\__SCRIPTS\_2VIDEOMASHUP\pragmatic-mote-340205-78677dda5561.json

### FULL CODE SCREENSHOT:
(MASH2) C:\Users\camer\Desktop\Video projects\__SCRIPTS\_2VIDEOMASHUP>Python __main__.py ./sp.mp4 ./final.mp4 "I will still love you, why are your hands so sweaty"
Traceback (most recent call last):
  File "__main__.py", line 24, in <module>
    Intelligence = IntelligenceService()
  File "C:\Users\camer\Desktop\Video projects\__SCRIPTS\_2VIDEOMASHUP\services\IntelligenceService.py", line 7, in __init__
    self.features = [videointelligence.enums.Feature.SPEECH_TRANSCRIPTION]
AttributeError: module 'google.cloud.videointelligence' has no attribute 'enums'

![image](https://user-images.githubusercontent.com/39450507/157291776-73a1400d-e18e-4520-a1a0-65c4cb6b6586.png)

**Comment by LamboCreeper** [comment]
Sorry for the late reply, but which version of Python and the dependencies are you using? I'm not getting the same error as you, so I'd like to try to replicate it as close as possible.

**Comment by scaruslooner** [comment]
No worries. I'm using python 3.6 
pip install google-cloud-videointelligence (2.6.1),  
pip install google-cloud-storage (2.2.1), 
pip install moviepy (1.0.3) 
![image](https://user-images.githubusercontent.com/39450507/158509262-4d38049d-e788-4aaa-9c51-c290e2dba989.png)

**Comment by LamboCreeper** [comment]
Hey @scaruslooner sorry for the delay, I hadn't had a chance to look into this.

I've pushed an update which has resolved these issues for me, could you try again using the latest changes on `master`? Thanks!

**Comment by scaruslooner** [comment]
Hello!
I tried the new update. And, I got a different error now lol.
I tried to run it twice one on python 3.6 and another on python 3.7. And I got the same error.
![image](https://user-images.githubusercontent.com/39450507/161402199-af5473d4-d081-4a15-ba0b-8b2a48e2c691.png)

Traceback (most recent call last):
  File "__main__.py", line 37, in <module>
    uploaded_file = Storage.upload(source, source)
  File "C:\Users\camer\Desktop\Video projects\__SCRIPTS\Video MashUp\services\StorageService.py", line 13, in upload
    blob.upload_from_filename(source)
  File "D:\_PROGRAMS\anaconda3NEW\envs\anyMash\lib\site-packages\google\cloud\storage\blob.py", line 2731, in upload_from_filename
    retry=retry,
  File "D:\_PROGRAMS\anaconda3NEW\envs\anyMash\lib\site-packages\google\cloud\storage\blob.py", line 2594, in upload_from_file
    _raise_from_invalid_response(exc)
  File "D:\_PROGRAMS\anaconda3NEW\envs\anyMash\lib\site-packages\google\cloud\storage\blob.py", line 4466, in _raise_from_invalid_response
    raise exceptions.from_http_status(response.status_code, message, response=response)
google.api_core.exceptions.Forbidden: 403 POST https://storage.googleapis.com/upload/storage/v1/b/my_storage_bucket/o?uploadType=resumable: {
  "error": {
    "code": 403,
    "message": "The billing account for the owning project is disabled in state closed",
    "errors": [
      {
        "message": "The billing account for the owning project is disabled in state closed",
        "domain": "global",
        "reason": "accountDisabled",
        "locationType": "header",
        "location": "Authorization"
      }
    ]
  }
}
: ('Request failed with status code', 403, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.CREATED: 201>)

**Comment by LamboCreeper** [comment]
Ah, I think you have billing disabled on your Google Cloud project. You'll need to enable it and attach a card.
